version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017" # Changed to 27018
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/datadoitDB

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
